version: '3'
services:
  # MongoDB service
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  # Backend service
  server:
    build: ./server
    container_name: mern_server
    restart: always
    ports:
      - '5000:5000'
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules

  # Frontend service
  client:
    build: ./client
    container_name: mern_client
    restart: always
    ports:
      - '5173:5173'
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongo_data:
